### ISSUE TITLE
instagram not working too

### ISSUE THREAD

**Issue by honeyhead** [dotnettools/SharpGrabber#66] opened 2022-01-28 09:36 UTC
I was test this url "https://www.instagram.com/p/CZRJeuUNXHV"

but not working and show this message "An item with the same key has already been added. Key: instapp:hashtags"

**Comment by javidsho** [comment] 2022-01-28 12:06
Duplicate of #65

**Closed by javidsho** 2022-01-28 12:06 UTC

**Comment by honeyhead** [comment] 2022-01-28 12:39
Well, this is not a private account content. So I don't think it's a certification service problem.

Do I need a authentication service that I don't know about?

**Comment by javidsho** [comment] 2022-01-28 13:33
Yeah, some time ago Instagram made authentication required for everyone and for all content including public posts.

**Comment by honeyhead** [comment] 2022-01-28 22:55
Thank you for your answer. There is definitely such a problem at the momentarily.

If I just bring it with HttpAgilityPack, there will be an error and I will test it with Selenium, so there was no problem.

If you do, you can consider bringing the PageSource to Selenium and then calculating it afterwards, but that's not what you want.

I'll tell you if I know how the header rule works when I bring media.
