### ISSUE TITLE
'The given key 'status' was not present in the dictionary.'

### ISSUE THREAD

**Issue by babakmdi** [dotnettools/SharpGrabber#34] opened 2021-06-17 10:32 UTC
after two or three request , i get this !

**Comment by babakmdi** [comment] 2021-06-17 15:06
https://www.youtube.com/watch?v=UJ0-i159JrE
https://www.youtube.com/watch?v=8kwDu3unlL0

i tried these links multiple times and randomly received that error

**Comment by snap608** [comment] 2021-06-18 13:43
Same here for any URLs I have tested now.

**Comment by JavidShoaei** [comment] 2021-06-18 15:08
The reason for this is very unclear, but I'm on it.

**Comment by snap608** [comment] 2021-06-18 15:17
A bit more stack trace for you. :)
```
System.Collections.Generic.KeyNotFoundException: The given key 'status' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DotNetTools.SharpGrabber.Internal.Grabbers.YouTubeGrabber.DownloadMetadata(String id, CancellationToken cancellationToken)
   at DotNetTools.SharpGrabber.Internal.Grabbers.YouTubeGrabber.GrabAsync(GrabResult result, String id, CancellationToken cancellationToken, GrabOptions options)
   at DotNetTools.SharpGrabber.Internal.Grabbers.YouTube.YouTubeGrabberBase.GrabAsync(Uri uri, CancellationToken cancellationToken, GrabOptions options)
```

**Comment by JavidShoaei** [comment] 2021-06-18 16:13
Good news! I almost fixed the error, in less than a few hours it'll be fixed.

**Comment by JavidShoaei** [comment] 2021-06-18 17:20
The issue is now fixed. Upgrade to `1.5.2`.

**Closed by JavidShoaei** 2021-06-18 17:20 UTC

**Comment by snap608** [comment] 2021-06-18 17:26
Works like a charm. Thank you. :)

**Comment by babakmdi** [comment] 2021-06-18 17:32
var result = await grabber.GrabAsync(new Uri(URL));
  the  CreationDate  is null 
   result.CreationDate = Null in the new version, can you fix this ?

**Comment by JavidShoaei** [comment] 2021-06-18 18:21
> 
> 
> var result = await grabber.GrabAsync(new Uri(URL));
> the CreationDate is null
> result.CreationDate = Null in the new version, can you fix this ?

Yeah, I saw that one. Couldn't come up with a quick fix and decided to release just as it, just "as it works".
I'm gonna start working on this soon.
