### ISSUE TITLE
Value cannot be null. (Parameter 'uriString')

### ISSUE THREAD

**Issue by alexrondao** [dotnettools/SharpGrabber#11] opened 2020-06-22 23:51 UTC
Hi, I'm trying to download a video from youtube. This video cannot be found or downloaded by SharpGrabber, there are some URLs, not all. Does anyone know why this happens? Is there something different in the video posted? If anyone can help with any tips or solutions. Thank you

**Comment by JavidShoaei** [comment] 2020-06-23 09:13
Hi there!
Can you please give me some examples of those URLs that work and those that don't?

**Comment by JavidShoaei** [comment] 2020-06-24 07:32
From what I see, the problem is with YouTube protected videos. I'm sorting it out.

**Comment by alexrondao** [comment] 2020-06-28 04:30
Hello, sorry for may ask later.

I cannot find this video https://www.youtube.com/watch?v=YSL7pb8RVwA
 BUT when I use this web site https://pt.savefrom.net/8/... find the video

Have something that I can do on the code to find?

Thanks

**Comment by JavidShoaei** [comment] 2020-06-28 09:20
I understand. I'm a little busy right now but I'm working on it. The problem is with the YouTube grabber and I'm debugging it right now.

**Comment by JavidShoaei** [comment] 2020-06-28 10:10
The issue is now fixed (PR #12). Please update your NuGet package to v1.2.0.

**Closed by JavidShoaei** 2020-06-28 10:10 UTC
